apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwOTIuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImNtVnphRzFoT2xKbGMyaHRZVUF4TWpNdUtnPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson